### ISSUE TITLE
yaml generation file

### ISSUE THREAD

**Issue by jarios86** [RTC-research-group/OpenNAS#16]
In the generation of yml file are missing some parameters:
- PDM module has not the config parameter 
`SHPF_FREQ_DIV       => x"05",`
`SLPF_FREQ_DIV       => x"06",`
`SLPF_SPIKES_DIV_FB  => x"734B",`
`SLPF_SPIKES_DIV_OUT => x"39C8",`
- There is missing one filter config parameters

**Comment by jpdominguez** [comment]
Fixed in [the latest push](https://github.com/RTC-research-group/OpenNAS/commit/1f37f1d711a30723bd2c885e43c4eb5f58c0a3f5).
